// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.dev.fluent;

import com.azure.core.annotation.ReturnType;
import com.azure.core.annotation.ServiceMethod;
import com.azure.core.http.rest.Response;
import com.azure.core.util.Context;
import com.azure.dev.fluent.models.PipelineGeneralSettingsInner;

/** An instance of this class provides access to all the operations defined in GeneralSettingsClient. */
public interface GeneralSettingsClient {
    /**
     * Gets pipeline general settings.
     *
     * @param organization The name of the Azure DevOps organization.
     * @param project Project ID or project name.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws com.azure.core.management.exception.ManagementException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return pipeline general settings.
     */
    @ServiceMethod(returns = ReturnType.SINGLE)
    PipelineGeneralSettingsInner get(String organization, String project);

    /**
     * Gets pipeline general settings.
     *
     * @param organization The name of the Azure DevOps organization.
     * @param project Project ID or project name.
     * @param context The context to associate with this operation.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws com.azure.core.management.exception.ManagementException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return pipeline general settings.
     */
    @ServiceMethod(returns = ReturnType.SINGLE)
    Response<PipelineGeneralSettingsInner> getWithResponse(String organization, String project, Context context);

    /**
     * Updates pipeline general settings.
     *
     * @param organization The name of the Azure DevOps organization.
     * @param project Project ID or project name.
     * @param body Contains pipeline general settings.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws com.azure.core.management.exception.ManagementException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return contains pipeline general settings.
     */
    @ServiceMethod(returns = ReturnType.SINGLE)
    PipelineGeneralSettingsInner update(String organization, String project, PipelineGeneralSettingsInner body);

    /**
     * Updates pipeline general settings.
     *
     * @param organization The name of the Azure DevOps organization.
     * @param project Project ID or project name.
     * @param body Contains pipeline general settings.
     * @param context The context to associate with this operation.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws com.azure.core.management.exception.ManagementException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return contains pipeline general settings.
     */
    @ServiceMethod(returns = ReturnType.SINGLE)
    Response<PipelineGeneralSettingsInner> updateWithResponse(
        String organization, String project, PipelineGeneralSettingsInner body, Context context);
}
