package io.weidongxu.util.releaseautomation.store;

public enum LiteReleaseState {
    VERIFICATION_FAILED,
    CODE_GEN_PIPELINE,
    CODE_GEN_FAILED,
    CODE_GEN_SUCCEEDED,
    CODE_GEN_PR_DRAFT,
    CODE_GEN_PR_READY,
    CODE_GEN_PR_APPROVED,
    CODE_GEN_PR_MERGE_FAILED,
    CODE_GEN_PR_MERGED,
    CODE_GEN_PR_CLOSED,
    CODE_GEN_PR_CI_SUCCEEDED,
    MULTIPLE_RELEASE_ARTIFACTS,
    RELEASE_CI,
    RELEASE_CI_NOT_FOUND,
    RELEASE_APPROVED,
    RELEASE_SUCCEEDED,
    VERSION_PR_NOT_FOUND,
    VERSION_PR_APPROVED,
    VERSION_PR_MERGE_FAILED,
    SUCCEEDED,
    UNKNOWN_EXCEPTION
}
