// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.dev.fluent.models;

import com.azure.core.annotation.Fluent;
import com.azure.dev.models.ReferenceLinks;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Represents an attachment to a build.
 */
@Fluent
public final class AttachmentInner {
    /*
     * The class to represent a collection of REST reference links.
     */
    @JsonProperty(value = "_links")
    private ReferenceLinks links;

    /*
     * The name of the attachment.
     */
    @JsonProperty(value = "name")
    private String name;

    /**
     * Creates an instance of AttachmentInner class.
     */
    public AttachmentInner() {
    }

    /**
     * Get the links property: The class to represent a collection of REST reference links.
     * 
     * @return the links value.
     */
    public ReferenceLinks links() {
        return this.links;
    }

    /**
     * Set the links property: The class to represent a collection of REST reference links.
     * 
     * @param links the links value to set.
     * @return the AttachmentInner object itself.
     */
    public AttachmentInner withLinks(ReferenceLinks links) {
        this.links = links;
        return this;
    }

    /**
     * Get the name property: The name of the attachment.
     * 
     * @return the name value.
     */
    public String name() {
        return this.name;
    }

    /**
     * Set the name property: The name of the attachment.
     * 
     * @param name the name value to set.
     * @return the AttachmentInner object itself.
     */
    public AttachmentInner withName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Validates the instance.
     * 
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    public void validate() {
        if (links() != null) {
            links().validate();
        }
    }
}
