// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.dev.fluent.models;

import com.azure.core.annotation.Fluent;
import com.azure.dev.models.RealtimeBuildEvent;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The BuildUpdatedEvent model.
 */
@Fluent
public class BuildUpdatedEventInner extends RealtimeBuildEvent {
    /*
     * Data representation of a build.
     */
    @JsonProperty(value = "build")
    private BuildInner build;

    /**
     * Creates an instance of BuildUpdatedEventInner class.
     */
    public BuildUpdatedEventInner() {
    }

    /**
     * Get the build property: Data representation of a build.
     * 
     * @return the build value.
     */
    public BuildInner build() {
        return this.build;
    }

    /**
     * Set the build property: Data representation of a build.
     * 
     * @param build the build value to set.
     * @return the BuildUpdatedEventInner object itself.
     */
    public BuildUpdatedEventInner withBuild(BuildInner build) {
        this.build = build;
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BuildUpdatedEventInner withBuildId(Integer buildId) {
        super.withBuildId(buildId);
        return this;
    }

    /**
     * Validates the instance.
     * 
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    @Override
    public void validate() {
        super.validate();
        if (build() != null) {
            build().validate();
        }
    }
}
