// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.dev.implementation;

import com.azure.dev.fluent.models.BuildMetricInner;
import com.azure.dev.models.BuildMetric;
import java.time.OffsetDateTime;

public final class BuildMetricImpl implements BuildMetric {
    private BuildMetricInner innerObject;

    private final com.azure.dev.DevManager serviceManager;

    BuildMetricImpl(BuildMetricInner innerObject, com.azure.dev.DevManager serviceManager) {
        this.innerObject = innerObject;
        this.serviceManager = serviceManager;
    }

    public OffsetDateTime date() {
        return this.innerModel().date();
    }

    public Integer intValue() {
        return this.innerModel().intValue();
    }

    public String name() {
        return this.innerModel().name();
    }

    public String scope() {
        return this.innerModel().scope();
    }

    public BuildMetricInner innerModel() {
        return this.innerObject;
    }

    private com.azure.dev.DevManager manager() {
        return this.serviceManager;
    }
}
