// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.dev.implementation;

import com.azure.dev.fluent.models.BuildDeletedEventInner;
import com.azure.dev.fluent.models.BuildInner;
import com.azure.dev.models.Build;
import com.azure.dev.models.BuildDeletedEvent;

public final class BuildDeletedEventImpl implements BuildDeletedEvent {
    private BuildDeletedEventInner innerObject;

    private final com.azure.dev.DevManager serviceManager;

    BuildDeletedEventImpl(BuildDeletedEventInner innerObject, com.azure.dev.DevManager serviceManager) {
        this.innerObject = innerObject;
        this.serviceManager = serviceManager;
    }

    public Integer buildId() {
        return this.innerModel().buildId();
    }

    public Build build() {
        BuildInner inner = this.innerModel().build();
        if (inner != null) {
            return new BuildImpl(inner, this.manager());
        } else {
            return null;
        }
    }

    public BuildDeletedEventInner innerModel() {
        return this.innerObject;
    }

    private com.azure.dev.DevManager manager() {
        return this.serviceManager;
    }
}
