// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.dev.implementation;

import com.azure.dev.fluent.models.BuildDefinitionReferenceInner;
import com.azure.dev.fluent.models.BuildInner;
import com.azure.dev.fluent.models.BuildMetricInner;
import com.azure.dev.models.AgentPoolQueue;
import com.azure.dev.models.Build;
import com.azure.dev.models.BuildDefinitionReference;
import com.azure.dev.models.BuildMetric;
import com.azure.dev.models.DefinitionQuality;
import com.azure.dev.models.DefinitionQueueStatus;
import com.azure.dev.models.DefinitionReference;
import com.azure.dev.models.DefinitionType;
import com.azure.dev.models.IdentityRef;
import com.azure.dev.models.ReferenceLinks;
import com.azure.dev.models.TeamProjectReference;
import java.time.OffsetDateTime;
import java.util.Collections;
import java.util.List;
import java.util.stream.Collectors;

public final class BuildDefinitionReferenceImpl implements BuildDefinitionReference {
    private BuildDefinitionReferenceInner innerObject;

    private final com.azure.dev.DevManager serviceManager;

    BuildDefinitionReferenceImpl(BuildDefinitionReferenceInner innerObject, com.azure.dev.DevManager serviceManager) {
        this.innerObject = innerObject;
        this.serviceManager = serviceManager;
    }

    public OffsetDateTime createdDate() {
        return this.innerModel().createdDate();
    }

    public Integer id() {
        return this.innerModel().id();
    }

    public String name() {
        return this.innerModel().name();
    }

    public String path() {
        return this.innerModel().path();
    }

    public TeamProjectReference project() {
        return this.innerModel().project();
    }

    public DefinitionQueueStatus queueStatus() {
        return this.innerModel().queueStatus();
    }

    public Integer revision() {
        return this.innerModel().revision();
    }

    public DefinitionType type() {
        return this.innerModel().type();
    }

    public String uri() {
        return this.innerModel().uri();
    }

    public String url() {
        return this.innerModel().url();
    }

    public ReferenceLinks links() {
        return this.innerModel().links();
    }

    public IdentityRef authoredBy() {
        return this.innerModel().authoredBy();
    }

    public DefinitionReference draftOf() {
        return this.innerModel().draftOf();
    }

    public List<DefinitionReference> drafts() {
        List<DefinitionReference> inner = this.innerModel().drafts();
        if (inner != null) {
            return Collections.unmodifiableList(inner);
        } else {
            return Collections.emptyList();
        }
    }

    public Build latestBuild() {
        BuildInner inner = this.innerModel().latestBuild();
        if (inner != null) {
            return new BuildImpl(inner, this.manager());
        } else {
            return null;
        }
    }

    public Build latestCompletedBuild() {
        BuildInner inner = this.innerModel().latestCompletedBuild();
        if (inner != null) {
            return new BuildImpl(inner, this.manager());
        } else {
            return null;
        }
    }

    public List<BuildMetric> metrics() {
        List<BuildMetricInner> inner = this.innerModel().metrics();
        if (inner != null) {
            return Collections.unmodifiableList(
                inner.stream().map(inner1 -> new BuildMetricImpl(inner1, this.manager())).collect(Collectors.toList()));
        } else {
            return Collections.emptyList();
        }
    }

    public DefinitionQuality quality() {
        return this.innerModel().quality();
    }

    public AgentPoolQueue queue() {
        return this.innerModel().queue();
    }

    public BuildDefinitionReferenceInner innerModel() {
        return this.innerObject;
    }

    private com.azure.dev.DevManager manager() {
        return this.serviceManager;
    }
}
