// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.dev.implementation;

import com.azure.dev.fluent.models.ChangeInner;
import com.azure.dev.models.Change;
import com.azure.dev.models.IdentityRef;
import java.time.OffsetDateTime;

public final class ChangeImpl implements Change {
    private ChangeInner innerObject;

    private final com.azure.dev.DevManager serviceManager;

    ChangeImpl(ChangeInner innerObject, com.azure.dev.DevManager serviceManager) {
        this.innerObject = innerObject;
        this.serviceManager = serviceManager;
    }

    public IdentityRef author() {
        return this.innerModel().author();
    }

    public String displayUri() {
        return this.innerModel().displayUri();
    }

    public String id() {
        return this.innerModel().id();
    }

    public String location() {
        return this.innerModel().location();
    }

    public String message() {
        return this.innerModel().message();
    }

    public Boolean messageTruncated() {
        return this.innerModel().messageTruncated();
    }

    public String pusher() {
        return this.innerModel().pusher();
    }

    public OffsetDateTime timestamp() {
        return this.innerModel().timestamp();
    }

    public String type() {
        return this.innerModel().type();
    }

    public ChangeInner innerModel() {
        return this.innerObject;
    }

    private com.azure.dev.DevManager manager() {
        return this.serviceManager;
    }
}
