// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.dev.implementation;

import com.azure.dev.fluent.models.PipelineGeneralSettingsInner;
import com.azure.dev.models.PipelineGeneralSettings;

public final class PipelineGeneralSettingsImpl implements PipelineGeneralSettings {
    private PipelineGeneralSettingsInner innerObject;

    private final com.azure.dev.DevManager serviceManager;

    PipelineGeneralSettingsImpl(PipelineGeneralSettingsInner innerObject, com.azure.dev.DevManager serviceManager) {
        this.innerObject = innerObject;
        this.serviceManager = serviceManager;
    }

    public Boolean enforceJobAuthScope() {
        return this.innerModel().enforceJobAuthScope();
    }

    public Boolean enforceReferencedRepoScopedToken() {
        return this.innerModel().enforceReferencedRepoScopedToken();
    }

    public Boolean enforceSettableVar() {
        return this.innerModel().enforceSettableVar();
    }

    public Boolean publishPipelineMetadata() {
        return this.innerModel().publishPipelineMetadata();
    }

    public Boolean statusBadgesArePrivate() {
        return this.innerModel().statusBadgesArePrivate();
    }

    public PipelineGeneralSettingsInner innerModel() {
        return this.innerObject;
    }

    private com.azure.dev.DevManager manager() {
        return this.serviceManager;
    }
}
