// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.dev.implementation;

import com.azure.dev.fluent.models.SourceRepositoryItemInner;
import com.azure.dev.models.SourceRepositoryItem;

public final class SourceRepositoryItemImpl implements SourceRepositoryItem {
    private SourceRepositoryItemInner innerObject;

    private final com.azure.dev.DevManager serviceManager;

    SourceRepositoryItemImpl(SourceRepositoryItemInner innerObject, com.azure.dev.DevManager serviceManager) {
        this.innerObject = innerObject;
        this.serviceManager = serviceManager;
    }

    public Boolean isContainer() {
        return this.innerModel().isContainer();
    }

    public String path() {
        return this.innerModel().path();
    }

    public String type() {
        return this.innerModel().type();
    }

    public String url() {
        return this.innerModel().url();
    }

    public SourceRepositoryItemInner innerModel() {
        return this.innerObject;
    }

    private com.azure.dev.DevManager manager() {
        return this.serviceManager;
    }
}
