// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

module com.azure.dev {
    requires transitive com.azure.core.management;

    exports com.azure.dev;
    exports com.azure.dev.fluent;
    exports com.azure.dev.fluent.models;
    exports com.azure.dev.models;

    opens com.azure.dev.fluent.models to
        com.azure.core,
        com.fasterxml.jackson.databind;
    opens com.azure.dev.models to
        com.azure.core,
        com.fasterxml.jackson.databind;
}
