// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.dev.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The AggregatedResultsDifference model.
 */
@Fluent
public final class AggregatedResultsDifference {
    /*
     * The increaseInDuration property.
     */
    @JsonProperty(value = "increaseInDuration")
    private String increaseInDuration;

    /*
     * The increaseInFailures property.
     */
    @JsonProperty(value = "increaseInFailures")
    private Integer increaseInFailures;

    /*
     * The increaseInNonImpactedTests property.
     */
    @JsonProperty(value = "increaseInNonImpactedTests")
    private Integer increaseInNonImpactedTests;

    /*
     * The increaseInOtherTests property.
     */
    @JsonProperty(value = "increaseInOtherTests")
    private Integer increaseInOtherTests;

    /*
     * The increaseInPassedTests property.
     */
    @JsonProperty(value = "increaseInPassedTests")
    private Integer increaseInPassedTests;

    /*
     * The increaseInTotalTests property.
     */
    @JsonProperty(value = "increaseInTotalTests")
    private Integer increaseInTotalTests;

    /**
     * Creates an instance of AggregatedResultsDifference class.
     */
    public AggregatedResultsDifference() {
    }

    /**
     * Get the increaseInDuration property: The increaseInDuration property.
     * 
     * @return the increaseInDuration value.
     */
    public String increaseInDuration() {
        return this.increaseInDuration;
    }

    /**
     * Set the increaseInDuration property: The increaseInDuration property.
     * 
     * @param increaseInDuration the increaseInDuration value to set.
     * @return the AggregatedResultsDifference object itself.
     */
    public AggregatedResultsDifference withIncreaseInDuration(String increaseInDuration) {
        this.increaseInDuration = increaseInDuration;
        return this;
    }

    /**
     * Get the increaseInFailures property: The increaseInFailures property.
     * 
     * @return the increaseInFailures value.
     */
    public Integer increaseInFailures() {
        return this.increaseInFailures;
    }

    /**
     * Set the increaseInFailures property: The increaseInFailures property.
     * 
     * @param increaseInFailures the increaseInFailures value to set.
     * @return the AggregatedResultsDifference object itself.
     */
    public AggregatedResultsDifference withIncreaseInFailures(Integer increaseInFailures) {
        this.increaseInFailures = increaseInFailures;
        return this;
    }

    /**
     * Get the increaseInNonImpactedTests property: The increaseInNonImpactedTests property.
     * 
     * @return the increaseInNonImpactedTests value.
     */
    public Integer increaseInNonImpactedTests() {
        return this.increaseInNonImpactedTests;
    }

    /**
     * Set the increaseInNonImpactedTests property: The increaseInNonImpactedTests property.
     * 
     * @param increaseInNonImpactedTests the increaseInNonImpactedTests value to set.
     * @return the AggregatedResultsDifference object itself.
     */
    public AggregatedResultsDifference withIncreaseInNonImpactedTests(Integer increaseInNonImpactedTests) {
        this.increaseInNonImpactedTests = increaseInNonImpactedTests;
        return this;
    }

    /**
     * Get the increaseInOtherTests property: The increaseInOtherTests property.
     * 
     * @return the increaseInOtherTests value.
     */
    public Integer increaseInOtherTests() {
        return this.increaseInOtherTests;
    }

    /**
     * Set the increaseInOtherTests property: The increaseInOtherTests property.
     * 
     * @param increaseInOtherTests the increaseInOtherTests value to set.
     * @return the AggregatedResultsDifference object itself.
     */
    public AggregatedResultsDifference withIncreaseInOtherTests(Integer increaseInOtherTests) {
        this.increaseInOtherTests = increaseInOtherTests;
        return this;
    }

    /**
     * Get the increaseInPassedTests property: The increaseInPassedTests property.
     * 
     * @return the increaseInPassedTests value.
     */
    public Integer increaseInPassedTests() {
        return this.increaseInPassedTests;
    }

    /**
     * Set the increaseInPassedTests property: The increaseInPassedTests property.
     * 
     * @param increaseInPassedTests the increaseInPassedTests value to set.
     * @return the AggregatedResultsDifference object itself.
     */
    public AggregatedResultsDifference withIncreaseInPassedTests(Integer increaseInPassedTests) {
        this.increaseInPassedTests = increaseInPassedTests;
        return this;
    }

    /**
     * Get the increaseInTotalTests property: The increaseInTotalTests property.
     * 
     * @return the increaseInTotalTests value.
     */
    public Integer increaseInTotalTests() {
        return this.increaseInTotalTests;
    }

    /**
     * Set the increaseInTotalTests property: The increaseInTotalTests property.
     * 
     * @param increaseInTotalTests the increaseInTotalTests value to set.
     * @return the AggregatedResultsDifference object itself.
     */
    public AggregatedResultsDifference withIncreaseInTotalTests(Integer increaseInTotalTests) {
        this.increaseInTotalTests = increaseInTotalTests;
        return this;
    }

    /**
     * Validates the instance.
     * 
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    public void validate() {
    }
}
