// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.dev.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.time.OffsetDateTime;

/**
 * A snapshot of build retention information. This class takes a sample at the given time. It provides information about
 * retained builds, files associated with those retained builds, and number of files being retained.
 */
@Fluent
public final class BuildRetentionSample {
    /*
     * Summary of retention by build
     */
    @JsonProperty(value = "builds")
    private String builds;

    /*
     * List of build definitions
     */
    @JsonProperty(value = "definitions")
    private String definitions;

    /*
     * Summary of files consumed by retained builds
     */
    @JsonProperty(value = "files")
    private String files;

    /*
     * The date and time when the sample was taken
     */
    @JsonProperty(value = "sampleTime")
    private OffsetDateTime sampleTime;

    /**
     * Creates an instance of BuildRetentionSample class.
     */
    public BuildRetentionSample() {
    }

    /**
     * Get the builds property: Summary of retention by build.
     * 
     * @return the builds value.
     */
    public String builds() {
        return this.builds;
    }

    /**
     * Set the builds property: Summary of retention by build.
     * 
     * @param builds the builds value to set.
     * @return the BuildRetentionSample object itself.
     */
    public BuildRetentionSample withBuilds(String builds) {
        this.builds = builds;
        return this;
    }

    /**
     * Get the definitions property: List of build definitions.
     * 
     * @return the definitions value.
     */
    public String definitions() {
        return this.definitions;
    }

    /**
     * Set the definitions property: List of build definitions.
     * 
     * @param definitions the definitions value to set.
     * @return the BuildRetentionSample object itself.
     */
    public BuildRetentionSample withDefinitions(String definitions) {
        this.definitions = definitions;
        return this;
    }

    /**
     * Get the files property: Summary of files consumed by retained builds.
     * 
     * @return the files value.
     */
    public String files() {
        return this.files;
    }

    /**
     * Set the files property: Summary of files consumed by retained builds.
     * 
     * @param files the files value to set.
     * @return the BuildRetentionSample object itself.
     */
    public BuildRetentionSample withFiles(String files) {
        this.files = files;
        return this;
    }

    /**
     * Get the sampleTime property: The date and time when the sample was taken.
     * 
     * @return the sampleTime value.
     */
    public OffsetDateTime sampleTime() {
        return this.sampleTime;
    }

    /**
     * Set the sampleTime property: The date and time when the sample was taken.
     * 
     * @param sampleTime the sampleTime value to set.
     * @return the BuildRetentionSample object itself.
     */
    public BuildRetentionSample withSampleTime(OffsetDateTime sampleTime) {
        this.sampleTime = sampleTime;
        return this;
    }

    /**
     * Validates the instance.
     * 
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    public void validate() {
    }
}
