// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.dev.models;

import com.azure.dev.fluent.models.BuildRetentionHistoryInner;
import java.util.List;

/**
 * An immutable client-side representation of BuildRetentionHistory.
 */
public interface BuildRetentionHistory {
    /**
     * Gets the buildRetentionSamples property: A list of builds that are older than the default retention policy, but
     * are not marked as retained. Something is causing these builds to not get cleaned up.
     * 
     * @return the buildRetentionSamples value.
     */
    List<BuildRetentionSample> buildRetentionSamples();

    /**
     * Gets the inner com.azure.dev.fluent.models.BuildRetentionHistoryInner object.
     * 
     * @return the inner object.
     */
    BuildRetentionHistoryInner innerModel();
}
