// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.dev.models;

import com.azure.core.annotation.Fluent;
import com.azure.core.util.logging.ClientLogger;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;
import java.util.UUID;

/** The BuildsDeletedEvent1 model. */
@Fluent
public class BuildsDeletedEvent1 {
    @JsonIgnore private final ClientLogger logger = new ClientLogger(BuildsDeletedEvent1.class);

    /*
     * The buildIds property.
     */
    @JsonProperty(value = "buildIds")
    private List<Integer> buildIds;

    /*
     * The ID of the definition.
     */
    @JsonProperty(value = "definitionId")
    private Integer definitionId;

    /*
     * The ID of the project.
     */
    @JsonProperty(value = "projectId")
    private UUID projectId;

    /**
     * Get the buildIds property: The buildIds property.
     *
     * @return the buildIds value.
     */
    public List<Integer> buildIds() {
        return this.buildIds;
    }

    /**
     * Set the buildIds property: The buildIds property.
     *
     * @param buildIds the buildIds value to set.
     * @return the BuildsDeletedEvent1 object itself.
     */
    public BuildsDeletedEvent1 withBuildIds(List<Integer> buildIds) {
        this.buildIds = buildIds;
        return this;
    }

    /**
     * Get the definitionId property: The ID of the definition.
     *
     * @return the definitionId value.
     */
    public Integer definitionId() {
        return this.definitionId;
    }

    /**
     * Set the definitionId property: The ID of the definition.
     *
     * @param definitionId the definitionId value to set.
     * @return the BuildsDeletedEvent1 object itself.
     */
    public BuildsDeletedEvent1 withDefinitionId(Integer definitionId) {
        this.definitionId = definitionId;
        return this;
    }

    /**
     * Get the projectId property: The ID of the project.
     *
     * @return the projectId value.
     */
    public UUID projectId() {
        return this.projectId;
    }

    /**
     * Set the projectId property: The ID of the project.
     *
     * @param projectId the projectId value to set.
     * @return the BuildsDeletedEvent1 object itself.
     */
    public BuildsDeletedEvent1 withProjectId(UUID projectId) {
        this.projectId = projectId;
        return this;
    }

    /**
     * Validates the instance.
     *
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    public void validate() {
    }
}
