// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.dev.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * The job authorization scope for builds queued against this definition.
 */
public enum BuildAuthorizationScope {
    /**
     * Enum value projectCollection.
     */
    PROJECT_COLLECTION("projectCollection"),

    /**
     * Enum value project.
     */
    PROJECT("project");

    /**
     * The actual serialized value for a BuildAuthorizationScope instance.
     */
    private final String value;

    BuildAuthorizationScope(String value) {
        this.value = value;
    }

    /**
     * Parses a serialized value to a BuildAuthorizationScope instance.
     * 
     * @param value the serialized value to parse.
     * @return the parsed BuildAuthorizationScope object, or null if unable to parse.
     */
    @JsonCreator
    public static BuildAuthorizationScope fromString(String value) {
        if (value == null) {
            return null;
        }
        BuildAuthorizationScope[] items = BuildAuthorizationScope.values();
        for (BuildAuthorizationScope item : items) {
            if (item.toString().equalsIgnoreCase(value)) {
                return item;
            }
        }
        return null;
    }

    /**
     * {@inheritDoc}
     */
    @JsonValue
    @Override
    public String toString() {
        return this.value;
    }
}
