// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.dev.models;

import com.azure.core.annotation.Fluent;
import com.azure.core.util.logging.ClientLogger;
import com.azure.dev.fluent.models.BuildMetricInner;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.time.OffsetDateTime;
import java.util.List;

/** For back-compat with extensions that use the old Steps format instead of Process and Phases. */
@Fluent
public class BuildDefinitionReference32 extends DefinitionReference {
    @JsonIgnore private final ClientLogger logger = new ClientLogger(BuildDefinitionReference32.class);

    /*
     * The class to represent a collection of REST reference links.
     */
    @JsonProperty(value = "_links")
    private ReferenceLinks links;

    /*
     * The author of the definition.
     */
    @JsonProperty(value = "authoredBy")
    private IdentityRef authoredBy;

    /*
     * A reference to the definition that this definition is a draft of, if
     * this is a draft definition.
     */
    @JsonProperty(value = "draftOf")
    private DefinitionReference draftOf;

    /*
     * The list of drafts associated with this definition, if this is not a
     * draft definition.
     */
    @JsonProperty(value = "drafts")
    private List<DefinitionReference> drafts;

    /*
     * The metrics property.
     */
    @JsonProperty(value = "metrics")
    private List<BuildMetricInner> metrics;

    /*
     * The quality of the definition document (draft, etc.)
     */
    @JsonProperty(value = "quality")
    private DefinitionQuality quality;

    /*
     * The default queue for builds run against this definition.
     */
    @JsonProperty(value = "queue")
    private AgentPoolQueue queue;

    /**
     * Get the links property: The class to represent a collection of REST reference links.
     *
     * @return the links value.
     */
    public ReferenceLinks links() {
        return this.links;
    }

    /**
     * Set the links property: The class to represent a collection of REST reference links.
     *
     * @param links the links value to set.
     * @return the BuildDefinitionReference32 object itself.
     */
    public BuildDefinitionReference32 withLinks(ReferenceLinks links) {
        this.links = links;
        return this;
    }

    /**
     * Get the authoredBy property: The author of the definition.
     *
     * @return the authoredBy value.
     */
    public IdentityRef authoredBy() {
        return this.authoredBy;
    }

    /**
     * Set the authoredBy property: The author of the definition.
     *
     * @param authoredBy the authoredBy value to set.
     * @return the BuildDefinitionReference32 object itself.
     */
    public BuildDefinitionReference32 withAuthoredBy(IdentityRef authoredBy) {
        this.authoredBy = authoredBy;
        return this;
    }

    /**
     * Get the draftOf property: A reference to the definition that this definition is a draft of, if this is a draft
     * definition.
     *
     * @return the draftOf value.
     */
    public DefinitionReference draftOf() {
        return this.draftOf;
    }

    /**
     * Set the draftOf property: A reference to the definition that this definition is a draft of, if this is a draft
     * definition.
     *
     * @param draftOf the draftOf value to set.
     * @return the BuildDefinitionReference32 object itself.
     */
    public BuildDefinitionReference32 withDraftOf(DefinitionReference draftOf) {
        this.draftOf = draftOf;
        return this;
    }

    /**
     * Get the drafts property: The list of drafts associated with this definition, if this is not a draft definition.
     *
     * @return the drafts value.
     */
    public List<DefinitionReference> drafts() {
        return this.drafts;
    }

    /**
     * Set the drafts property: The list of drafts associated with this definition, if this is not a draft definition.
     *
     * @param drafts the drafts value to set.
     * @return the BuildDefinitionReference32 object itself.
     */
    public BuildDefinitionReference32 withDrafts(List<DefinitionReference> drafts) {
        this.drafts = drafts;
        return this;
    }

    /**
     * Get the metrics property: The metrics property.
     *
     * @return the metrics value.
     */
    public List<BuildMetricInner> metrics() {
        return this.metrics;
    }

    /**
     * Set the metrics property: The metrics property.
     *
     * @param metrics the metrics value to set.
     * @return the BuildDefinitionReference32 object itself.
     */
    public BuildDefinitionReference32 withMetrics(List<BuildMetricInner> metrics) {
        this.metrics = metrics;
        return this;
    }

    /**
     * Get the quality property: The quality of the definition document (draft, etc.).
     *
     * @return the quality value.
     */
    public DefinitionQuality quality() {
        return this.quality;
    }

    /**
     * Set the quality property: The quality of the definition document (draft, etc.).
     *
     * @param quality the quality value to set.
     * @return the BuildDefinitionReference32 object itself.
     */
    public BuildDefinitionReference32 withQuality(DefinitionQuality quality) {
        this.quality = quality;
        return this;
    }

    /**
     * Get the queue property: The default queue for builds run against this definition.
     *
     * @return the queue value.
     */
    public AgentPoolQueue queue() {
        return this.queue;
    }

    /**
     * Set the queue property: The default queue for builds run against this definition.
     *
     * @param queue the queue value to set.
     * @return the BuildDefinitionReference32 object itself.
     */
    public BuildDefinitionReference32 withQueue(AgentPoolQueue queue) {
        this.queue = queue;
        return this;
    }

    /** {@inheritDoc} */
    @Override
    public BuildDefinitionReference32 withCreatedDate(OffsetDateTime createdDate) {
        super.withCreatedDate(createdDate);
        return this;
    }

    /** {@inheritDoc} */
    @Override
    public BuildDefinitionReference32 withId(Integer id) {
        super.withId(id);
        return this;
    }

    /** {@inheritDoc} */
    @Override
    public BuildDefinitionReference32 withName(String name) {
        super.withName(name);
        return this;
    }

    /** {@inheritDoc} */
    @Override
    public BuildDefinitionReference32 withPath(String path) {
        super.withPath(path);
        return this;
    }

    /** {@inheritDoc} */
    @Override
    public BuildDefinitionReference32 withProject(TeamProjectReference project) {
        super.withProject(project);
        return this;
    }

    /** {@inheritDoc} */
    @Override
    public BuildDefinitionReference32 withQueueStatus(DefinitionQueueStatus queueStatus) {
        super.withQueueStatus(queueStatus);
        return this;
    }

    /** {@inheritDoc} */
    @Override
    public BuildDefinitionReference32 withRevision(Integer revision) {
        super.withRevision(revision);
        return this;
    }

    /** {@inheritDoc} */
    @Override
    public BuildDefinitionReference32 withType(DefinitionType type) {
        super.withType(type);
        return this;
    }

    /** {@inheritDoc} */
    @Override
    public BuildDefinitionReference32 withUri(String uri) {
        super.withUri(uri);
        return this;
    }

    /** {@inheritDoc} */
    @Override
    public BuildDefinitionReference32 withUrl(String url) {
        super.withUrl(url);
        return this;
    }

    /**
     * Validates the instance.
     *
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    @Override
    public void validate() {
        super.validate();
        if (links() != null) {
            links().validate();
        }
        if (authoredBy() != null) {
            authoredBy().validate();
        }
        if (draftOf() != null) {
            draftOf().validate();
        }
        if (drafts() != null) {
            drafts().forEach(e -> e.validate());
        }
        if (metrics() != null) {
            metrics().forEach(e -> e.validate());
        }
        if (queue() != null) {
            queue().validate();
        }
    }
}
