// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.dev.models;

import com.azure.core.annotation.Fluent;
import com.azure.core.util.logging.ClientLogger;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;
import java.util.UUID;

/** The ConsoleLogEvent model. */
@Fluent
public final class ConsoleLogEvent extends RealtimeBuildEvent {
    @JsonIgnore private final ClientLogger logger = new ClientLogger(ConsoleLogEvent.class);

    /*
     * The lines property.
     */
    @JsonProperty(value = "lines")
    private List<String> lines;

    /*
     * The stepRecordId property.
     */
    @JsonProperty(value = "stepRecordId")
    private UUID stepRecordId;

    /*
     * The timelineId property.
     */
    @JsonProperty(value = "timelineId")
    private UUID timelineId;

    /*
     * The timelineRecordId property.
     */
    @JsonProperty(value = "timelineRecordId")
    private UUID timelineRecordId;

    /**
     * Get the lines property: The lines property.
     *
     * @return the lines value.
     */
    public List<String> lines() {
        return this.lines;
    }

    /**
     * Set the lines property: The lines property.
     *
     * @param lines the lines value to set.
     * @return the ConsoleLogEvent object itself.
     */
    public ConsoleLogEvent withLines(List<String> lines) {
        this.lines = lines;
        return this;
    }

    /**
     * Get the stepRecordId property: The stepRecordId property.
     *
     * @return the stepRecordId value.
     */
    public UUID stepRecordId() {
        return this.stepRecordId;
    }

    /**
     * Set the stepRecordId property: The stepRecordId property.
     *
     * @param stepRecordId the stepRecordId value to set.
     * @return the ConsoleLogEvent object itself.
     */
    public ConsoleLogEvent withStepRecordId(UUID stepRecordId) {
        this.stepRecordId = stepRecordId;
        return this;
    }

    /**
     * Get the timelineId property: The timelineId property.
     *
     * @return the timelineId value.
     */
    public UUID timelineId() {
        return this.timelineId;
    }

    /**
     * Set the timelineId property: The timelineId property.
     *
     * @param timelineId the timelineId value to set.
     * @return the ConsoleLogEvent object itself.
     */
    public ConsoleLogEvent withTimelineId(UUID timelineId) {
        this.timelineId = timelineId;
        return this;
    }

    /**
     * Get the timelineRecordId property: The timelineRecordId property.
     *
     * @return the timelineRecordId value.
     */
    public UUID timelineRecordId() {
        return this.timelineRecordId;
    }

    /**
     * Set the timelineRecordId property: The timelineRecordId property.
     *
     * @param timelineRecordId the timelineRecordId value to set.
     * @return the ConsoleLogEvent object itself.
     */
    public ConsoleLogEvent withTimelineRecordId(UUID timelineRecordId) {
        this.timelineRecordId = timelineRecordId;
        return this;
    }

    /** {@inheritDoc} */
    @Override
    public ConsoleLogEvent withBuildId(Integer buildId) {
        super.withBuildId(buildId);
        return this;
    }

    /**
     * Validates the instance.
     *
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    @Override
    public void validate() {
        super.validate();
    }
}
