// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.dev.models;

import com.azure.core.annotation.Fluent;
import com.azure.core.util.logging.ClientLogger;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;

/** Configuration parameters of the pipeline. */
@Fluent
public final class CreatePipelineConfigurationParameters {
    @JsonIgnore private final ClientLogger logger = new ClientLogger(CreatePipelineConfigurationParameters.class);

    /*
     * Type of configuration.
     */
    @JsonProperty(value = "type")
    private ConfigurationType type;

    /**
     * Get the type property: Type of configuration.
     *
     * @return the type value.
     */
    public ConfigurationType type() {
        return this.type;
    }

    /**
     * Set the type property: Type of configuration.
     *
     * @param type the type value to set.
     * @return the CreatePipelineConfigurationParameters object itself.
     */
    public CreatePipelineConfigurationParameters withType(ConfigurationType type) {
        this.type = type;
        return this;
    }

    /**
     * Validates the instance.
     *
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    public void validate() {
    }
}
