// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.dev.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.time.OffsetDateTime;

/**
 * Represents a reference to a definition.
 */
@Fluent
public class DefinitionReference {
    /*
     * The date this version of the definition was created.
     */
    @JsonProperty(value = "createdDate")
    private OffsetDateTime createdDate;

    /*
     * The ID of the referenced definition.
     */
    @JsonProperty(value = "id")
    private Integer id;

    /*
     * The name of the referenced definition.
     */
    @JsonProperty(value = "name")
    private String name;

    /*
     * The folder path of the definition.
     */
    @JsonProperty(value = "path")
    private String path;

    /*
     * A reference to the project.
     */
    @JsonProperty(value = "project")
    private TeamProjectReference project;

    /*
     * A value that indicates whether builds can be queued against this definition.
     */
    @JsonProperty(value = "queueStatus")
    private DefinitionQueueStatus queueStatus;

    /*
     * The definition revision number.
     */
    @JsonProperty(value = "revision")
    private Integer revision;

    /*
     * The type of the definition.
     */
    @JsonProperty(value = "type")
    private DefinitionType type;

    /*
     * The definition's URI.
     */
    @JsonProperty(value = "uri")
    private String uri;

    /*
     * The REST URL of the definition.
     */
    @JsonProperty(value = "url")
    private String url;

    /**
     * Creates an instance of DefinitionReference class.
     */
    public DefinitionReference() {
    }

    /**
     * Get the createdDate property: The date this version of the definition was created.
     * 
     * @return the createdDate value.
     */
    public OffsetDateTime createdDate() {
        return this.createdDate;
    }

    /**
     * Set the createdDate property: The date this version of the definition was created.
     * 
     * @param createdDate the createdDate value to set.
     * @return the DefinitionReference object itself.
     */
    public DefinitionReference withCreatedDate(OffsetDateTime createdDate) {
        this.createdDate = createdDate;
        return this;
    }

    /**
     * Get the id property: The ID of the referenced definition.
     * 
     * @return the id value.
     */
    public Integer id() {
        return this.id;
    }

    /**
     * Set the id property: The ID of the referenced definition.
     * 
     * @param id the id value to set.
     * @return the DefinitionReference object itself.
     */
    public DefinitionReference withId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Get the name property: The name of the referenced definition.
     * 
     * @return the name value.
     */
    public String name() {
        return this.name;
    }

    /**
     * Set the name property: The name of the referenced definition.
     * 
     * @param name the name value to set.
     * @return the DefinitionReference object itself.
     */
    public DefinitionReference withName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get the path property: The folder path of the definition.
     * 
     * @return the path value.
     */
    public String path() {
        return this.path;
    }

    /**
     * Set the path property: The folder path of the definition.
     * 
     * @param path the path value to set.
     * @return the DefinitionReference object itself.
     */
    public DefinitionReference withPath(String path) {
        this.path = path;
        return this;
    }

    /**
     * Get the project property: A reference to the project.
     * 
     * @return the project value.
     */
    public TeamProjectReference project() {
        return this.project;
    }

    /**
     * Set the project property: A reference to the project.
     * 
     * @param project the project value to set.
     * @return the DefinitionReference object itself.
     */
    public DefinitionReference withProject(TeamProjectReference project) {
        this.project = project;
        return this;
    }

    /**
     * Get the queueStatus property: A value that indicates whether builds can be queued against this definition.
     * 
     * @return the queueStatus value.
     */
    public DefinitionQueueStatus queueStatus() {
        return this.queueStatus;
    }

    /**
     * Set the queueStatus property: A value that indicates whether builds can be queued against this definition.
     * 
     * @param queueStatus the queueStatus value to set.
     * @return the DefinitionReference object itself.
     */
    public DefinitionReference withQueueStatus(DefinitionQueueStatus queueStatus) {
        this.queueStatus = queueStatus;
        return this;
    }

    /**
     * Get the revision property: The definition revision number.
     * 
     * @return the revision value.
     */
    public Integer revision() {
        return this.revision;
    }

    /**
     * Set the revision property: The definition revision number.
     * 
     * @param revision the revision value to set.
     * @return the DefinitionReference object itself.
     */
    public DefinitionReference withRevision(Integer revision) {
        this.revision = revision;
        return this;
    }

    /**
     * Get the type property: The type of the definition.
     * 
     * @return the type value.
     */
    public DefinitionType type() {
        return this.type;
    }

    /**
     * Set the type property: The type of the definition.
     * 
     * @param type the type value to set.
     * @return the DefinitionReference object itself.
     */
    public DefinitionReference withType(DefinitionType type) {
        this.type = type;
        return this;
    }

    /**
     * Get the uri property: The definition's URI.
     * 
     * @return the uri value.
     */
    public String uri() {
        return this.uri;
    }

    /**
     * Set the uri property: The definition's URI.
     * 
     * @param uri the uri value to set.
     * @return the DefinitionReference object itself.
     */
    public DefinitionReference withUri(String uri) {
        this.uri = uri;
        return this;
    }

    /**
     * Get the url property: The REST URL of the definition.
     * 
     * @return the url value.
     */
    public String url() {
        return this.url;
    }

    /**
     * Set the url property: The REST URL of the definition.
     * 
     * @param url the url value to set.
     * @return the DefinitionReference object itself.
     */
    public DefinitionReference withUrl(String url) {
        this.url = url;
        return this;
    }

    /**
     * Validates the instance.
     * 
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    public void validate() {
        if (project() != null) {
            project().validate();
        }
    }
}
