// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.dev.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/** Defines values for DefinitionQueryOrder. */
public enum DefinitionQueryOrder {
    /** Enum value none. */
    NONE("none"),

    /** Enum value lastModifiedAscending. */
    LAST_MODIFIED_ASCENDING("lastModifiedAscending"),

    /** Enum value lastModifiedDescending. */
    LAST_MODIFIED_DESCENDING("lastModifiedDescending"),

    /** Enum value definitionNameAscending. */
    DEFINITION_NAME_ASCENDING("definitionNameAscending"),

    /** Enum value definitionNameDescending. */
    DEFINITION_NAME_DESCENDING("definitionNameDescending");

    /** The actual serialized value for a DefinitionQueryOrder instance. */
    private final String value;

    DefinitionQueryOrder(String value) {
        this.value = value;
    }

    /**
     * Parses a serialized value to a DefinitionQueryOrder instance.
     *
     * @param value the serialized value to parse.
     * @return the parsed DefinitionQueryOrder object, or null if unable to parse.
     */
    @JsonCreator
    public static DefinitionQueryOrder fromString(String value) {
        DefinitionQueryOrder[] items = DefinitionQueryOrder.values();
        for (DefinitionQueryOrder item : items) {
            if (item.toString().equalsIgnoreCase(value)) {
                return item;
            }
        }
        return null;
    }

    @JsonValue
    @Override
    public String toString() {
        return this.value;
    }
}
