// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.dev.models;

import com.azure.core.annotation.Fluent;

/**
 * Represents the target for the docker build process.
 */
@Fluent
public final class DockerProcessTarget extends DesignerProcessTarget {
    /**
     * Creates an instance of DockerProcessTarget class.
     */
    public DockerProcessTarget() {
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DockerProcessTarget withAgentSpecification(AgentSpecification agentSpecification) {
        super.withAgentSpecification(agentSpecification);
        return this;
    }

    /**
     * Validates the instance.
     * 
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    @Override
    public void validate() {
        super.validate();
    }
}
