// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.dev.models;

import com.azure.core.annotation.Fluent;
import com.azure.core.util.logging.ClientLogger;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;

/** Represents the ability to build forks of the selected repository. */
@Fluent
public final class Forks {
    @JsonIgnore private final ClientLogger logger = new ClientLogger(Forks.class);

    /*
     * Indicates whether a build should use secrets when building forks of the
     * selected repository.
     */
    @JsonProperty(value = "allowSecrets")
    private Boolean allowSecrets;

    /*
     * Indicates whether the trigger should queue builds for forks of the
     * selected repository.
     */
    @JsonProperty(value = "enabled")
    private Boolean enabled;

    /**
     * Get the allowSecrets property: Indicates whether a build should use secrets when building forks of the selected
     * repository.
     *
     * @return the allowSecrets value.
     */
    public Boolean allowSecrets() {
        return this.allowSecrets;
    }

    /**
     * Set the allowSecrets property: Indicates whether a build should use secrets when building forks of the selected
     * repository.
     *
     * @param allowSecrets the allowSecrets value to set.
     * @return the Forks object itself.
     */
    public Forks withAllowSecrets(Boolean allowSecrets) {
        this.allowSecrets = allowSecrets;
        return this;
    }

    /**
     * Get the enabled property: Indicates whether the trigger should queue builds for forks of the selected repository.
     *
     * @return the enabled value.
     */
    public Boolean enabled() {
        return this.enabled;
    }

    /**
     * Set the enabled property: Indicates whether the trigger should queue builds for forks of the selected repository.
     *
     * @param enabled the enabled value to set.
     * @return the Forks object itself.
     */
    public Forks withEnabled(Boolean enabled) {
        this.enabled = enabled;
        return this;
    }

    /**
     * Validates the instance.
     *
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    public void validate() {
    }
}
