// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.dev.models;

import com.azure.core.http.rest.Response;
import com.azure.core.util.Context;

/**
 * Resource collection API of Histories.
 */
public interface Histories {
    /**
     * Returns the retention history for the project collection. This includes pipelines that have custom retention
     * rules that may prevent the retention job from cleaning them up, runs per pipeline with retention type, files
     * associated with pipelines owned by the collection with retention type, and the number of files per pipeline.
     * 
     * @param organization The name of the Azure DevOps organization.
     * @param daysToLookback The daysToLookback parameter.
     * @param context The context to associate with this operation.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws com.azure.core.management.exception.ManagementException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return a historical overview of build retention information along with {@link Response}.
     */
    Response<BuildRetentionHistory> getWithResponse(String organization, Integer daysToLookback, Context context);

    /**
     * Returns the retention history for the project collection. This includes pipelines that have custom retention
     * rules that may prevent the retention job from cleaning them up, runs per pipeline with retention type, files
     * associated with pipelines owned by the collection with retention type, and the number of files per pipeline.
     * 
     * @param organization The name of the Azure DevOps organization.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws com.azure.core.management.exception.ManagementException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return a historical overview of build retention information.
     */
    BuildRetentionHistory get(String organization);
}
