// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.dev.models;

import com.azure.core.annotation.Fluent;
import com.azure.core.util.logging.ClientLogger;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;

/** Represents an entry in a workspace mapping. */
@Fluent
public final class MappingDetails {
    @JsonIgnore private final ClientLogger logger = new ClientLogger(MappingDetails.class);

    /*
     * The local path.
     */
    @JsonProperty(value = "localPath")
    private String localPath;

    /*
     * The mapping type.
     */
    @JsonProperty(value = "mappingType")
    private String mappingType;

    /*
     * The server path.
     */
    @JsonProperty(value = "serverPath")
    private String serverPath;

    /**
     * Get the localPath property: The local path.
     *
     * @return the localPath value.
     */
    public String localPath() {
        return this.localPath;
    }

    /**
     * Set the localPath property: The local path.
     *
     * @param localPath the localPath value to set.
     * @return the MappingDetails object itself.
     */
    public MappingDetails withLocalPath(String localPath) {
        this.localPath = localPath;
        return this;
    }

    /**
     * Get the mappingType property: The mapping type.
     *
     * @return the mappingType value.
     */
    public String mappingType() {
        return this.mappingType;
    }

    /**
     * Set the mappingType property: The mapping type.
     *
     * @param mappingType the mappingType value to set.
     * @return the MappingDetails object itself.
     */
    public MappingDetails withMappingType(String mappingType) {
        this.mappingType = mappingType;
        return this;
    }

    /**
     * Get the serverPath property: The server path.
     *
     * @return the serverPath value.
     */
    public String serverPath() {
        return this.serverPath;
    }

    /**
     * Set the serverPath property: The server path.
     *
     * @param serverPath the serverPath value to set.
     * @return the MappingDetails object itself.
     */
    public MappingDetails withServerPath(String serverPath) {
        this.serverPath = serverPath;
        return this;
    }

    /**
     * Validates the instance.
     *
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    public void validate() {
    }
}
