// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.dev.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Represents options for running a phase against multiple agents.
 */
@Fluent
public final class MultipleAgentExecutionOptions extends AgentTargetExecutionOptions {
    /*
     * Indicates whether failure on one agent should prevent the phase from running on other agents.
     */
    @JsonProperty(value = "continueOnError")
    private Boolean continueOnError;

    /*
     * The maximum number of agents to use simultaneously.
     */
    @JsonProperty(value = "maxConcurrency")
    private Integer maxConcurrency;

    /**
     * Creates an instance of MultipleAgentExecutionOptions class.
     */
    public MultipleAgentExecutionOptions() {
    }

    /**
     * Get the continueOnError property: Indicates whether failure on one agent should prevent the phase from running on
     * other agents.
     * 
     * @return the continueOnError value.
     */
    public Boolean continueOnError() {
        return this.continueOnError;
    }

    /**
     * Set the continueOnError property: Indicates whether failure on one agent should prevent the phase from running on
     * other agents.
     * 
     * @param continueOnError the continueOnError value to set.
     * @return the MultipleAgentExecutionOptions object itself.
     */
    public MultipleAgentExecutionOptions withContinueOnError(Boolean continueOnError) {
        this.continueOnError = continueOnError;
        return this;
    }

    /**
     * Get the maxConcurrency property: The maximum number of agents to use simultaneously.
     * 
     * @return the maxConcurrency value.
     */
    public Integer maxConcurrency() {
        return this.maxConcurrency;
    }

    /**
     * Set the maxConcurrency property: The maximum number of agents to use simultaneously.
     * 
     * @param maxConcurrency the maxConcurrency value to set.
     * @return the MultipleAgentExecutionOptions object itself.
     */
    public MultipleAgentExecutionOptions withMaxConcurrency(Integer maxConcurrency) {
        this.maxConcurrency = maxConcurrency;
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MultipleAgentExecutionOptions withType(Integer type) {
        super.withType(type);
        return this;
    }

    /**
     * Validates the instance.
     * 
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    @Override
    public void validate() {
        super.validate();
    }
}
