// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.dev.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/** Defines values for ProcessTemplateType. */
public enum ProcessTemplateType {
    /** Enum value custom. */
    CUSTOM("custom"),

    /** Enum value default. */
    DEFAULT("default"),

    /** Enum value upgrade. */
    UPGRADE("upgrade");

    /** The actual serialized value for a ProcessTemplateType instance. */
    private final String value;

    ProcessTemplateType(String value) {
        this.value = value;
    }

    /**
     * Parses a serialized value to a ProcessTemplateType instance.
     *
     * @param value the serialized value to parse.
     * @return the parsed ProcessTemplateType object, or null if unable to parse.
     */
    @JsonCreator
    public static ProcessTemplateType fromString(String value) {
        ProcessTemplateType[] items = ProcessTemplateType.values();
        for (ProcessTemplateType item : items) {
            if (item.toString().equalsIgnoreCase(value)) {
                return item;
            }
        }
        return null;
    }

    @JsonValue
    @Override
    public String toString() {
        return this.value;
    }
}
