// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.dev.models;

import com.azure.dev.fluent.models.RunInner;
import java.time.OffsetDateTime;
import java.util.Map;

/**
 * An immutable client-side representation of Run.
 */
public interface Run {
    /**
     * Gets the id property: The id property.
     * 
     * @return the id value.
     */
    Integer id();

    /**
     * Gets the name property: The name property.
     * 
     * @return the name value.
     */
    String name();

    /**
     * Gets the links property: The class to represent a collection of REST reference links.
     * 
     * @return the links value.
     */
    ReferenceLinks links();

    /**
     * Gets the createdDate property: The createdDate property.
     * 
     * @return the createdDate value.
     */
    OffsetDateTime createdDate();

    /**
     * Gets the finalYaml property: The finalYaml property.
     * 
     * @return the finalYaml value.
     */
    String finalYaml();

    /**
     * Gets the finishedDate property: The finishedDate property.
     * 
     * @return the finishedDate value.
     */
    OffsetDateTime finishedDate();

    /**
     * Gets the pipeline property: A reference to a Pipeline.
     * 
     * @return the pipeline value.
     */
    PipelineReference pipeline();

    /**
     * Gets the resources property: The resources property.
     * 
     * @return the resources value.
     */
    RunResources resources();

    /**
     * Gets the result property: The result property.
     * 
     * @return the result value.
     */
    RunResult result();

    /**
     * Gets the state property: The state property.
     * 
     * @return the state value.
     */
    RunState state();

    /**
     * Gets the templateParameters property: Dictionary of &lt;AnyObject&gt;.
     * 
     * @return the templateParameters value.
     */
    Map<String, Object> templateParameters();

    /**
     * Gets the url property: The url property.
     * 
     * @return the url value.
     */
    String url();

    /**
     * Gets the variables property: Dictionary of &lt;Variable&gt;.
     * 
     * @return the variables value.
     */
    Map<String, Variable> variables();

    /**
     * Gets the inner com.azure.dev.fluent.models.RunInner object.
     * 
     * @return the inner object.
     */
    RunInner innerModel();
}
