// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.dev.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Represents a phase target that runs on the server.
 */
@Fluent
public final class ServerTarget extends PhaseTarget {
    /*
     * The execution options.
     */
    @JsonProperty(value = "executionOptions")
    private ServerTargetExecutionOptions executionOptions;

    /**
     * Creates an instance of ServerTarget class.
     */
    public ServerTarget() {
    }

    /**
     * Get the executionOptions property: The execution options.
     * 
     * @return the executionOptions value.
     */
    public ServerTargetExecutionOptions executionOptions() {
        return this.executionOptions;
    }

    /**
     * Set the executionOptions property: The execution options.
     * 
     * @param executionOptions the executionOptions value to set.
     * @return the ServerTarget object itself.
     */
    public ServerTarget withExecutionOptions(ServerTargetExecutionOptions executionOptions) {
        this.executionOptions = executionOptions;
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ServerTarget withType(Integer type) {
        super.withType(type);
        return this;
    }

    /**
     * Validates the instance.
     * 
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    @Override
    public void validate() {
        super.validate();
        if (executionOptions() != null) {
            executionOptions().validate();
        }
    }
}
