// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.dev.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/** Defines values for ValidationResult. */
public enum ValidationResult {
    /** Enum value ok. */
    OK("ok"),

    /** Enum value warning. */
    WARNING("warning"),

    /** Enum value error. */
    ERROR("error");

    /** The actual serialized value for a ValidationResult instance. */
    private final String value;

    ValidationResult(String value) {
        this.value = value;
    }

    /**
     * Parses a serialized value to a ValidationResult instance.
     *
     * @param value the serialized value to parse.
     * @return the parsed ValidationResult object, or null if unable to parse.
     */
    @JsonCreator
    public static ValidationResult fromString(String value) {
        ValidationResult[] items = ValidationResult.values();
        for (ValidationResult item : items) {
            if (item.toString().equalsIgnoreCase(value)) {
                return item;
            }
        }
        return null;
    }

    @JsonValue
    @Override
    public String toString() {
        return this.value;
    }
}
