// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.dev.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The Variable model.
 */
@Fluent
public final class Variable {
    /*
     * The isSecret property.
     */
    @JsonProperty(value = "isSecret")
    private Boolean isSecret;

    /*
     * The value property.
     */
    @JsonProperty(value = "value")
    private String value;

    /**
     * Creates an instance of Variable class.
     */
    public Variable() {
    }

    /**
     * Get the isSecret property: The isSecret property.
     * 
     * @return the isSecret value.
     */
    public Boolean isSecret() {
        return this.isSecret;
    }

    /**
     * Set the isSecret property: The isSecret property.
     * 
     * @param isSecret the isSecret value to set.
     * @return the Variable object itself.
     */
    public Variable withIsSecret(Boolean isSecret) {
        this.isSecret = isSecret;
        return this;
    }

    /**
     * Get the value property: The value property.
     * 
     * @return the value value.
     */
    public String value() {
        return this.value;
    }

    /**
     * Set the value property: The value property.
     * 
     * @param value the value value to set.
     * @return the Variable object itself.
     */
    public Variable withValue(String value) {
        this.value = value;
        return this;
    }

    /**
     * Validates the instance.
     * 
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    public void validate() {
    }
}
